# Generated by Django 3.1.7 on 2021-12-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='ig_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
