# Generated by Django 3.1.7 on 2021-12-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20211210_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_time',
            field=models.DateTimeField(),
        ),
    ]
