# Generated by Django 3.1.7 on 2021-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20211210_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chunk',
            name='user_notsent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunk',
            name='user_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
